name: Push to Docker Hub

on: push

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-java-webapp-container:latest
    - name: Push the docker image to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/    alpine-java-webapp-container:latest
  